version: '3.8'

services:
  backend:
    container_name: pos-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: sh docker/scripts/Entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env  
    depends_on:
      - postgres
    volumes:
      - .:/app 


  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./envs/postgres.env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


volumes:
  postgres_data:
    driver: local
